alter table EMST_CARD_REQUEST add (CRQ_PAID_STATE NUMBER(1, 0)  DEFAULT 0);
alter table EMST_CARD_REQUEST add CRQ_PAID_DATE TIMESTAMP(6);

create INDEX "IX_CRQ_PAID_STATUS" ON "EMST_CARD_REQUEST" ("CRQ_PAID_STATE");
create INDEX "IX_CRQ_PAID_DATE" ON "EMST_CARD_REQUEST" ("CRQ_PAID_DATE");

