CREATE SEQUENCE "SEQ_EMST_MESSAGE_PERSON" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_MESSAGE_PERSON 
(
  MESSPER_ID NUMBER(19, 0) NOT NULL 
, MESSPER_PERSON_ID NUMBER(19, 0) 
, MESSPER_MESSAGE_ID NUMBER(19, 0) 
, MESSPER_READ_STATE VARCHAR2(20 CHAR) 
, CONSTRAINT PK_MESSPER_ID PRIMARY KEY 
  (
    MESSPER_ID 
  )
); 

ALTER TABLE EMST_MESSAGE_PERSON
ADD CONSTRAINT CKC_MESSPER_READ_STATE CHECK 
(MESSPER_READ_STATE IN ('R','U'))
ENABLE;
