  ---------------------------------------------------------------------------------
  
  CREATE TABLE "EMST_PREPARED_MESSAGE"
  (
    "PRE_MESS_ID"      NUMBER(19,0) NOT NULL ENABLE,
    "PRE_MESS_CREATE_DATE" TIMESTAMP(6) ,
    "PRE_MESS_TITLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PRE_MESS_CONTENT" CLOB,
    "PRE_MESS_SENDER_USERNAME" varchar2(255 BYTE),
    "PRE_MESS_FILE"  BLOB,
    "PRE_MESS_HAS_FILE" NUMBER(1,0),
    "PRE_MESS_ISALL" NUMBER(1,0),
    "PRE_MESS_ISMANAGER" NUMBER(1,0),
    "PRE_MESS_ISOFFICE" NUMBER(1,0),
    "PRE_MESS_ISNOCR" NUMBER(1,0),
    "PRE_MESS_STATE" VARCHAR2(255 BYTE) ,
    "PRE_MESS_FILE_NAME" VARCHAR2(255 BYTE) ,
    "PRE_MESS_FILE_TYPE" VARCHAR2(255 BYTE) ,
    
    CONSTRAINT "EMST_PREPARED_MESSAGE_PK" PRIMARY KEY ("PRE_MESS_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING TABLESPACE "TS_NOCR_EMS" ENABLE
  )
	
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "TS_NOCR_EMS" ;
  ---------------------------------------------------------------------------
  CREATE SEQUENCE "SEQ_EMST_PRE_MESSAGE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER NOCYCLE ;

  
  ---------------------------------------------------------------------------  
  
  