
package ws.web.ems.nocr.gam.com;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BaseException", targetNamespace = "http://ws.web.ems.nocr.gam.com/")
public class BaseException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BaseException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BaseException_Exception(String message, BaseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BaseException_Exception(String message, BaseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.web.ems.nocr.gam.com.BaseException
     */
    public BaseException getFaultInfo() {
        return faultInfo;
    }

}
