
package ws.web.ems.nocr.gam.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardRequestStateWS", targetNamespace = "http://ws.web.ems.nocr.gam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardRequestStateWS {


    /**
     * 
     * @param nationalId
     * @param mobile
     * @return
     *     returns java.lang.String
     * @throws BaseException_Exception
     * @throws InternalException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkCardRequestState", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckCardRequestState")
    @ResponseWrapper(localName = "checkCardRequestStateResponse", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckCardRequestStateResponse")
    @Action(input = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkCardRequestStateRequest", output = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkCardRequestStateResponse", fault = {
        @FaultAction(className = InternalException.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkCardRequestState/Fault/InternalException"),
        @FaultAction(className = BaseException_Exception.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkCardRequestState/Fault/BaseException")
    })
    public String checkCardRequestState(
        @WebParam(name = "NationalId", targetNamespace = "")
        String nationalId,
        @WebParam(name = "Mobile", targetNamespace = "")
        String mobile)
        throws BaseException_Exception, InternalException
    ;

    /**
     * 
     * @param trackingId
     * @return
     *     returns java.lang.String
     * @throws BaseException_Exception
     * @throws InternalException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkTrackingId", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckTrackingId")
    @ResponseWrapper(localName = "checkTrackingIdResponse", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckTrackingIdResponse")
    @Action(input = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkTrackingIdRequest", output = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkTrackingIdResponse", fault = {
        @FaultAction(className = InternalException.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkTrackingId/Fault/InternalException"),
        @FaultAction(className = BaseException_Exception.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkTrackingId/Fault/BaseException")
    })
    public String checkTrackingId(
        @WebParam(name = "TrackingId", targetNamespace = "")
        String trackingId)
        throws BaseException_Exception, InternalException
    ;

    /**
     * 
     * @param birthCertificateSeries
     * @param nationalId
     * @param citizenBirthDate
     * @return
     *     returns java.lang.String
     * @throws BaseException_Exception
     * @throws InternalException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkBirthCertificateSerial", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckBirthCertificateSerial")
    @ResponseWrapper(localName = "checkBirthCertificateSerialResponse", targetNamespace = "http://ws.web.ems.nocr.gam.com/", className = "ws.web.ems.nocr.gam.com.CheckBirthCertificateSerialResponse")
    @Action(input = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkBirthCertificateSerialRequest", output = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkBirthCertificateSerialResponse", fault = {
        @FaultAction(className = InternalException.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkBirthCertificateSerial/Fault/InternalException"),
        @FaultAction(className = BaseException_Exception.class, value = "http://ws.web.ems.nocr.gam.com/CardRequestStateWS/checkBirthCertificateSerial/Fault/BaseException")
    })
    public String checkBirthCertificateSerial(
        @WebParam(name = "NationalId", targetNamespace = "")
        String nationalId,
        @WebParam(name = "BirthCertificateSeries", targetNamespace = "")
        String birthCertificateSeries,
        @WebParam(name = "CitizenBirthDate", targetNamespace = "")
        String citizenBirthDate)
        throws BaseException_Exception, InternalException
    ;

}
