
package est;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "iMSException", targetNamespace = "http://nims.manipardaz.com/")
public class IMSException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IMSException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IMSException_Exception(String message, IMSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IMSException_Exception(String message, IMSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: est.IMSException
     */
    public IMSException getFaultInfo() {
        return faultInfo;
    }

}
