
package est;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImsServiceService", targetNamespace = "http://ims.nocr.org", wsdlLocation = "http://10.7.17.186/imsWebService/ImsServiceService?WSDL")
public class ImsServiceService
    extends Service
{

    private final static URL IMSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IMSSERVICESERVICE_EXCEPTION;
    private final static QName IMSSERVICESERVICE_QNAME = new QName("http://ims.nocr.org", "ImsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.7.17.186/imsWebService/ImsServiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMSSERVICESERVICE_WSDL_LOCATION = url;
        IMSSERVICESERVICE_EXCEPTION = e;
    }

    public ImsServiceService() {
        super(__getWsdlLocation(), IMSSERVICESERVICE_QNAME);
    }

    public ImsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMSSERVICESERVICE_QNAME, features);
    }

    public ImsServiceService(URL wsdlLocation) {
        super(wsdlLocation, IMSSERVICESERVICE_QNAME);
    }

    public ImsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMSSERVICESERVICE_QNAME, features);
    }

    public ImsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImsService
     */
    @WebEndpoint(name = "ImsServiceServicePort")
    public ImsService getImsServiceServicePort() {
        return super.getPort(new QName("http://ims.nocr.org", "ImsServiceServicePort"), ImsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImsService
     */
    @WebEndpoint(name = "ImsServiceServicePort")
    public ImsService getImsServiceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ims.nocr.org", "ImsServiceServicePort"), ImsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMSSERVICESERVICE_EXCEPTION!= null) {
            throw IMSSERVICESERVICE_EXCEPTION;
        }
        return IMSSERVICESERVICE_WSDL_LOCATION;
    }

}
