
package est;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImsService", targetNamespace = "http://nims.manipardaz.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImsService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns est.TransferInfo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/updateCitizenInfoRequest", output = "http://nims.manipardaz.com/ImsService/updateCitizenInfoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nims.manipardaz.com/ImsService/updateCitizenInfo/Fault/Exception")
    })
    public TransferInfo updateCitizenInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        TransferInfo arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns est.TransferInfo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/getUpdatedCitizensResultRequest", output = "http://nims.manipardaz.com/ImsService/getUpdatedCitizensResultResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nims.manipardaz.com/ImsService/getUpdatedCitizensResult/Fault/Exception")
    })
    public TransferInfo getUpdatedCitizensResult(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/setCitizenCardDeliveredRequest", output = "http://nims.manipardaz.com/ImsService/setCitizenCardDeliveredResponse")
    public String setCitizenCardDelivered(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        CardDeliverInfo arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/setCitizenCardRevokedRequest", output = "http://nims.manipardaz.com/ImsService/setCitizenCardRevokedResponse")
    public String setCitizenCardRevoked(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        CardRevokedInfo arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns est.Result
     * @throws IMSException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/runQueryRequest", output = "http://nims.manipardaz.com/ImsService/runQueryResponse", fault = {
        @FaultAction(className = IMSException_Exception.class, value = "http://nims.manipardaz.com/ImsService/runQuery/Fault/iMSException")
    })
    public Result runQuery(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0)
        throws IMSException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns est.Result
     * @throws IMSException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/getIMSPhotosRequest", output = "http://nims.manipardaz.com/ImsService/getIMSPhotosResponse", fault = {
        @FaultAction(className = IMSException_Exception.class, value = "http://nims.manipardaz.com/ImsService/getIMSPhotos/Fault/iMSException")
    })
    public Result getIMSPhotos(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0)
        throws IMSException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns est.TransferInfo
     * @throws IMSException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/getFaceRequest", output = "http://nims.manipardaz.com/ImsService/getFaceResponse", fault = {
        @FaultAction(className = IMSException_Exception.class, value = "http://nims.manipardaz.com/ImsService/getFace/Fault/iMSException")
    })
    public TransferInfo getFace(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2)
        throws IMSException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns est.TransferInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/fetchCitizenInfoRequest", output = "http://nims.manipardaz.com/ImsService/fetchCitizenInfoResponse")
    public TransferInfo fetchCitizenInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns est.TransferInfo
     * @throws IMSException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/getBodyRequest", output = "http://nims.manipardaz.com/ImsService/getBodyResponse", fault = {
        @FaultAction(className = IMSException_Exception.class, value = "http://nims.manipardaz.com/ImsService/getBody/Fault/iMSException")
    })
    public TransferInfo getBody(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2)
        throws IMSException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://nims.manipardaz.com/ImsService/getVersionRequest", output = "http://nims.manipardaz.com/ImsService/getVersionResponse")
    public String getVersion();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IMSException_Exception
     */
    @WebMethod
    @Action(input = "http://nims.manipardaz.com/ImsService/sendResponseRequest", output = "http://nims.manipardaz.com/ImsService/sendResponseResponse", fault = {
        @FaultAction(className = IMSException_Exception.class, value = "http://nims.manipardaz.com/ImsService/sendResponse/Fault/iMSException")
    })
    public void sendResponse(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        byte arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws IMSException_Exception
    ;

}
