
package est;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Estelam", targetNamespace = "http://est", wsdlLocation = "http://webservice-idc.nocrservices.org/iwsd/Estelam?wsdl")
public class Estelam
    extends Service
{

    private final static URL ESTELAM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(est.Estelam.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = est.Estelam.class.getResource(".");
            url = new URL(baseUrl, "http://webservice-idc.nocrservices.org/iwsd/Estelam?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservice-idc.nocrservices.org/iwsd/Estelam?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ESTELAM_WSDL_LOCATION = url;
    }

    public Estelam(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Estelam() {
        super(ESTELAM_WSDL_LOCATION, new QName("http://est", "Estelam"));
    }

    /**
     * 
     * @return
     *     returns EstelamPort
     */
    @WebEndpoint(name = "EstelamPort")
    public EstelamPort getEstelamPort() {
        return super.getPort(new QName("http://est", "EstelamPort"), EstelamPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstelamPort
     */
    @WebEndpoint(name = "EstelamPort")
    public EstelamPort getEstelamPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://est", "EstelamPort"), EstelamPort.class, features);
    }

}
