
package est;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Estelam", targetNamespace = "http://est", wsdlLocation = "http://10.7.17.122:7001/iws/Estelam?wsdl")
public class Estelam
    extends Service
{

    private final static URL ESTELAM_WSDL_LOCATION;
    private final static WebServiceException ESTELAM_EXCEPTION;
    private final static QName ESTELAM_QNAME = new QName("http://est", "Estelam");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.7.17.122:7001/iws/Estelam?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTELAM_WSDL_LOCATION = url;
        ESTELAM_EXCEPTION = e;
    }

    public Estelam() {
        super(__getWsdlLocation(), ESTELAM_QNAME);
    }

    public Estelam(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTELAM_QNAME, features);
    }

    public Estelam(URL wsdlLocation) {
        super(wsdlLocation, ESTELAM_QNAME);
    }

    public Estelam(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTELAM_QNAME, features);
    }

    public Estelam(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Estelam(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstelamPort
     */
    @WebEndpoint(name = "EstelamPort")
    public EstelamPort getEstelamPort() {
        return super.getPort(new QName("http://est", "EstelamPort"), EstelamPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstelamPort
     */
    @WebEndpoint(name = "EstelamPort")
    public EstelamPort getEstelamPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://est", "EstelamPort"), EstelamPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTELAM_EXCEPTION!= null) {
            throw ESTELAM_EXCEPTION;
        }
        return ESTELAM_WSDL_LOCATION;
    }

}
