
package est;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception3F", targetNamespace = "http://est")
public class Exception3F_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Exception3F faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception3F_Exception(String message, Exception3F faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception3F_Exception(String message, Exception3F faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: est.Exception3F
     */
    public Exception3F getFaultInfo() {
        return faultInfo;
    }

}
