
package est;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnsupportedEncodingException", targetNamespace = "http://est")
public class UnsupportedEncodingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnsupportedEncodingException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnsupportedEncodingException_Exception(String message, UnsupportedEncodingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnsupportedEncodingException_Exception(String message, UnsupportedEncodingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: est.UnsupportedEncodingException
     */
    public UnsupportedEncodingException getFaultInfo() {
        return faultInfo;
    }

}
