alter table emst_card_request drop column CRQ_ESTELAM2_FLAG;

alter Table EMST_CARD_REQUEST
add (CRQ_ESTELAM2_FLAG VARCHAR2(1 CHAR));

ALTER TABLE EMST_CARD_REQUEST
ADD CONSTRAINT CKC_CRQ_ESTELAM2_FLAG CHECK 
(CRQ_ESTELAM2_FLAG IN ('O', 'R','V', 'N'))
ENABLE;


---------------------------------------------

CREATE SEQUENCE "SEQ_EMST_ESTELAM2_FAILURE_LOG" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_ESTELAM2_FAILURE_LOG 
(
  ESL_ID NUMBER(19, 0) NOT NULL 
, ESL_CREATE_DATE TIMESTAMP(6) NOT NULL 
, ESL_NATIONAL_ID VARCHAR2(10 CHAR) NOT NULL 
, ESL_DESCRIPTION VARCHAR2(300 BYTE) 
, ESL_TYPE VARCHAR2(255 CHAR) 
, ESL_RESOLVED VARCHAR2(1 BYTE)
, CONSTRAINT PK_ESL_ID PRIMARY KEY 
  (
    ESL_ID 
  )

);


ALTER TABLE EMST_ESTELAM2_FAILURE_LOG
ADD CONSTRAINT CKC_ESL_TYPE CHECK 
(ESL_TYPE IN ('NOT_FOUND', 'NOT_GENDER_EQUAL', 'INVAILD_CERTIFICATE_ID', 
'INVAILD_BIRTH_DATE', 'INVAILD_CERTIFICATE_SERIAL', 'INVAILD_NAME', 'INVAILD_LAST_NAME', 
'INVAILD_FATHER_NAME', 'INVAILD_GENDER','UNKNOWN_IMS_MESSAGE'))
ENABLE;

--ALTER TABLE EMST_ESTELAM2_FAILURE_LOG
--ADD CONSTRAINT CKC_ESL_TYPE CHECK 
--(ESL_TYPE IN ('INVAILD_DATA', 'NOT_FOUND'))
--ENABLE;

ALTER TABLE EMST_ESTELAM2_FAILURE_LOG
ADD CONSTRAINT CKC_ESL_RESOLVED CHECK 
(ESL_RESOLVED IN ('T', 'F'))
ENABLE;