CREATE  INDEX "IX_CRQ_ESTELAM2_FLAG" ON "EMST_CARD_REQUEST" ("CRQ_ESTELAM2_FLAG");
CREATE  INDEX "IX_CRQ_CMS_REQ_ID" ON "EMST_CARD_REQUEST" ("CRQ_CMS_REQ_ID");

CREATE  INDEX "IX_ESL_NATIONAL_ID" ON "EMST_ESTELAM2_FAILURE_LOG" ("ESL_NATIONAL_ID");