 CREATE TABLE "EMST_CARD_REQUEST_BLOBS"
  (
    "CRQ_BLOBS_ID"      NUMBER(19,0) NOT NULL ENABLE,
    "CRQ_BLOBS_CRQ_ID"      NUMBER(19,0) NOT NULL ENABLE,
    "CRQ_BLOBS_SIGNED_RECEIPT" BLOB,
    "CRQ_BLOBS_RECEIPT_TEXT" CLOB,
    "CRQ_BLOBS_OFFICER_SIGN" BLOB,

    CONSTRAINT "EMST_CARD_REQUEST_BLOBS_PK" PRIMARY KEY ("CRQ_BLOBS_ID"),
    CONSTRAINT "EMST_CARD_REQUEST_FK" FOREIGN KEY ("CRQ_BLOBS_CRQ_ID") REFERENCES "EMST_CARD_REQUEST" ("CRQ_ID") ON DELETE CASCADE ENABLE
  );
  
  create INDEX "IX_CRQ_BLOBS_CRQ" ON "EMST_CARD_REQUEST_BLOBS" ("CRQ_BLOBS_CRQ_ID");
	
  ---------------------------------------------------------------------------
  CREATE SEQUENCE "SEQ_EMS_CARD_REQUEST_BLOBS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER NOCYCLE ;

  
  ---------------------------------------------------
  
  CREATE TABLE "EMST_CARD_REQUEST_BLOBS"
  (
    "CRQ_BLOBS_ID"      NUMBER(19,0) NOT NULL ENABLE,
    "CRQ_BLOBS_SIGNED_RECEIPT" BLOB,
    "CRQ_BLOBS_RECEIPT_TEXT" CLOB,
    "CRQ_BLOBS_OFFICER_SIGN" BLOB,

    CONSTRAINT "PK_CRQ_BLOBS_" PRIMARY KEY ("CRQ_BLOBS_ID"),
    CONSTRAINT "FK_CRQ_BLOBS_CARDREQ" FOREIGN KEY ("CRQ_BLOBS_ID") REFERENCES "EMST_CARD_REQUEST" ("CRQ_ID") ON DELETE CASCADE ENABLE
  );
  
  
  ---------------------------------------------------------------------------

    
  create /*+ NOLOGGING */ table EMST_CARD_REQUEST_BLOBS tablespace TS_NOCR_EMS_LOB as
  select 
  CRQ_ID as CRQ_BLOBS_ID, 
  CRQ_OFFICER_SIGN as CRQ_BLOBS_OFFICER_SIGN, 
  CRQ_SIGNED_RECEIPT as CRQ_BLOBS_SIGNED_RECEIPT, 
  CRQ_RECEIPT_TEXT as  CRQ_BLOBS_RECEIPT_TEXT
  from EMST_CARD_REQUEST;
  
   ALTER TABLE EMST_CARD_REQUEST_BLOBS ADD CONSTRAINT PK_CRQ_BLOBS PRIMARY KEY ("CRQ_BLOBS_ID");
   ALTER TABLE EMST_CARD_REQUEST_BLOBS ADD CONSTRAINT FK_CRQ_BLOBS_CARDREQ FOREIGN KEY ("CRQ_BLOBS_ID") REFERENCES "EMST_CARD_REQUEST" ("CRQ_ID") ON DELETE CASCADE ENABLE;
   
   alter table EMST_CARD_REQUEST drop column CRQ_OFFICER_SIGN;
   alter table EMST_CARD_REQUEST drop column CRQ_SIGNED_RECEIPT;
   alter table EMST_CARD_REQUEST drop column CRQ_RECEIPT_TEXT;
   -----------------------------------------------------------------------------
   
alter table EMST_CARD_REQUEST rename column crq_metadata to crq_metadata_old;
alter table EMST_CARD_REQUEST add crq_metadata varchar2(4000 CHAR);

alter table EMST_CARD_REQUEST disable all triggers;
update /*+ NOLOGGING PARALLEL(4) */ EMST_CARD_REQUEST set crq_metadata = crq_metadata_old;
alter table EMST_CARD_REQUEST enable all triggers;

alter table EMST_CARD_REQUEST drop column crq_metadata_old;