

--------------------------------------------- New Query
CREATE TABLE EMST_IMS_EST_IMAGE 
(
  IEI_ID NUMBER(19, 0) NOT NULL ,
  IEI_NATIONAL_IMAGE BLOB ,
  IEI_NATIONAL_ID VARCHAR2(10 CHAR),
  
  CONSTRAINT "PK_IEI_ID" PRIMARY KEY ("IEI_ID"),
  CONSTRAINT "FK_IEI_CITIZEN" FOREIGN KEY ("IEI_ID") REFERENCES "EMST_CITIZEN" ("CTZ_ID") ON DELETE CASCADE ENABLE
); 

CREATE INDEX "IX_IEI_NATIONAL_ID" ON "EMST_IMS_EST_IMAGE" ("IEI_NATIONAL_ID");

------------------------------------------------
