
CREATE SEQUENCE "SEQ_EMST_NIST_HEADER" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_NIST_HEADER 
(
  	NIS_ID NUMBER(19, 0) NOT NULL 
, 	NIS_DATA BLOB NOT NULL 
,	NIS_REQUEST_ID NUMBER(19, 0) NOT NULL
, 	NIS_CREATE_DATE TIMESTAMP(6) NOT NULL
, 
	CONSTRAINT PK_NIS_ID PRIMARY KEY 
  (
    	NIS_ID
  ),
  	CONSTRAINT "FK_REQUEST_ID" FOREIGN KEY ("NIS_REQUEST_ID") REFERENCES "EMST_CARD_REQUEST" ("CRQ_ID") on delete cascade ENABLE
); 


--ALTER TABLE EMST_NIST_HEADER
--ADD CONSTRAINT FK_REQUEST_ID FOREIGN KEY
--(
--  NIS_REQUEST_ID 
--)
--REFERENCES EMST_CARD_REQUEST
--(
--  CRQ_ID 
--)
--on delete cascade;