alter table emst_person_token add PTK_DELIVER_DATE TIMESTAMP(6);

Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (GAS_SEQ_GAST_ACCESS_ID.NEXTVAL,'ems_activateToken','Y','مدیریت فعالسازی توکن');

alter table EMST_WORKSTATION add CONSTRAINT AK_ACTIVATION_CODE_unique UNIQUE (WST_ACTIVATION_CODE);

Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (GAS_SEQ_GAST_ACCESS_ID.NEXTVAL,'ems_renewPersonToken','Y','مدیریت درخواست تمدید توکن');

Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (GAS_SEQ_GAST_ACCESS_ID.NEXTVAL,'ems_viewPersonTokenList','Y','مشاهده فهرست توکنهای کاربر');

Insert into INFT_PROFILE_KEY (PRF_ID,PRF_PARENT_ID,PRF_SYS_ID,PRF_NAME,PRF_PRIORITY_CHAIN,PRF_STATUS,PRF_ICON_CLASS,PRF_PER_ACCESS,PRF_DEP_ACCESS,PRF_SYS_ACCESS) values (6000,3,1,'nocr.ems.profile.signatureTokenExpireNotificationDays','S,D,P','H',null,null,null,null);

Insert into INFT_SYSTEM_PROFILE (SPF_ID,SPF_PRF_ID,SPF_DATE,SPF_CLOB) values (6000,6000,null,21);

Insert into INFT_PROFILE_KEY (PRF_ID,PRF_PARENT_ID,PRF_SYS_ID,PRF_NAME,PRF_PRIORITY_CHAIN,PRF_STATUS,PRF_ICON_CLASS,PRF_PER_ACCESS,PRF_DEP_ACCESS,PRF_SYS_ACCESS) values (6001,3,1,'nocr.ems.profile.autoAcceptRenewalRequest','S,D,P','H',null,null,null,null);

Insert into INFT_SYSTEM_PROFILE (SPF_ID,SPF_PRF_ID,SPF_DATE,SPF_CLOB) values (6001,6001,null,0);

alter table EMST_PERSON_TOKEN drop constraint CKC_PTK_STATE;

alter table EMST_PERSON_TOKEN add constraint CKC_PTK_STATE check
(PTK_STATE in( 'READY_TO_ISSUE','PENDING_TO_ISSUE','READY_TO_DELIVER','DELIVERED','REVOKED','PKI_ERROR','PROCESSED','WAITING_FOR_PICKUP','PICKUP_IN_PROGRESS','PENDING_FOR_EMS','READY_TO_RENEWAL_ISSUE','PENDING_TO_RENEWAL_ISSUE','READY_TO_RENEWAL_DELIVER','EMS_REJECT','SUSPENDED'));