
CREATE SEQUENCE "SEQ_EMST_PHOTO_VIP" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_PHOTO_VIP 
(
  PHV_ID NUMBER(19, 0) NOT NULL 
, PHV_DATA BLOB NOT NULL 
, PHV_CARD_REQUEST_ID NUMBER(19, 0) NOT NULL 
, PHV_META_DATA VARCHAR2(300 BYTE)  
, CONSTRAINT PK_PHV_ID PRIMARY KEY 
  (
    PHV_ID 
  )
); 

ALTER TABLE EMST_PHOTO_VIP
ADD CONSTRAINT FK_PHV_CARD_REQUEST_ID FOREIGN KEY
(
  PHV_CARD_REQUEST_ID 
)
REFERENCES EMST_CARD_REQUEST
(
  CRQ_ID 
)