----------------------------------emst_report_file-----------------------------------


------------------ALTER TABLE EMST_REPORT_FILE DISABLE constraint SYS_C0042531;------------------------



--------007
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (1000,1000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (1001,1000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (1002,1000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (1003,1000,'SUB_REPORT','subReport1','XLS');



--------008
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (2000,2000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (2001,2000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (2002,2000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (2003,2000,'SUB_REPORT','subReport1','XLS');



--------008-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (3000,3000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (3001,3000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (3002,3000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (3003,3000,'SUB_REPORT','subReport1','XLS');



--------010
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (4000,4000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (4001,4000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (4002,4000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (4003,4000,'SUB_REPORT','subReport1','XLS');



--------010-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (5000,5000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (5001,5000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (5002,5000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (5003,5000,'SUB_REPORT','subReport1','XLS');



--------011
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (6000,6000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (6001,6000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (6002,6000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (6003,6000,'SUB_REPORT','subReport1','XLS');



--------011-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (7000,7000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (7001,7000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (7002,7000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (7003,7000,'SUB_REPORT','subReport1','XLS');



--------012
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (8000,8000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (8001,8000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (8002,8000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (8003,8000,'SUB_REPORT','subReport1','XLS');



--------012-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (9000,9000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (9001,9000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (9002,9000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (9003,9000,'SUB_REPORT','subReport1','XLS');



--------013
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (10000,10000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (10001,10000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (10002,10000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (10003,10000,'SUB_REPORT','subReport1','XLS');



--------013-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (11000,11000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (11001,11000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (11002,11000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (11003,11000,'SUB_REPORT','subReport1','XLS');



--------014
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (12000,12000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (12001,12000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (12002,12000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (12003,12000,'SUB_REPORT','subReport1','XLS');



--------014-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (13000,13000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (13001,13000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (13002,13000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (13003,13000,'SUB_REPORT','subReport1','XLS');



--------015
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (14000,14000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (10001,14000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (14002,14000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (14003,14000,'SUB_REPORT','subReport1','XLS');



--------015-2
Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (15000,15000,'MASTER_REPORT',null,'PDF');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (15001,15000,'SUB_REPORT','subReport1','PDF');


Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (15002,15000,'MASTER_REPORT',null,'XLS');

Insert into EMST_REPORT_FILE (RPF_ID,RPF_REPORT_ID,RPF_TYPE,RPF_CAPTION,RPF_OUTPUT_TYPE) values (15003,15000,'SUB_REPORT','subReport1','XLS');




----------------------------ALTER TABLE EMST_REPORT_FILE ENABLE constraint SYS_C0042531;-----------------------------------

