Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3034,'ems_rpt_request_state','Y','گزارش وضعیت های درخواست');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3035,'ems_rpt_issued_card','Y','گزارش کارت های صادر شده');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3036,'ems_rpt_user_action','Y','گزارش فعالیت کاربران');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3037,'ems_rpt_pending_issuance','Y','گزارش درخواست های منتظر صدور');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3038,'ems_rpt_request_sum_by_province','Y','گزارش مجموع درخواست ها بر اساس استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3039,'ems_rpt_citizen_info','Y','گزارش اطلاعات شهروندان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3040,'ems_rpt_enrollment_activate','Y','گزارش فعالیت دفاتر');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values (3041,'ems_rpt_enrollment_state','Y','گزارش وضعیت دفاتر');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3042, '﻿ems_rpt_citizen_info' , 'Y' , '﻿گزارش آماری ثبت نام کنندگان به تفکیک جنسیت، دین و گروه سنی');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3045, 'ems_rpt_repeal_request' , 'Y' , 'گزارش آماری درخواست های باطل شده به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3046, 'ems_rpt_repeal_request2' , 'Y' , 'گزارش آماری درخواست های باطل شده به تفکیک ادارات');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3047, 'ems_rpt_repeal_card' , 'Y' , 'گزارش آماری کارت های باطل شده به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3048, 'ems_rpt_repeal_card2' , 'Y' , 'گزارش آماری کارت های باطل شده به تفکیک ادارات');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3049, 'ems_rpt_missed_card' , 'Y' , 'گزارش آماری کارت های گم شده و دریافت نشده به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3050, 'ems_rpt_missed_card2' , 'Y' , 'گزارش آماری کارت های گم شده و دریافت نشده به تفکیک ادارات');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3051, 'ems_rpt_request_reason' , 'Y' , 'گزارش آماری علت درخواست به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3052, 'ems_rpt_request_reason2' , 'Y' , 'گزارش آماری علت درخواست به تفکیک ادارات');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3053, 'ems_rpt_Minutia_request' , 'Y' , 'گزارش آماری وضعیت آثار انگشتان درخواست‌های ثبت‌نام شده به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3054, 'ems_rpt_Minutia_request2' , 'Y' , 'گزارش آماری وضعیت آثار انگشتان درخواست‌های ثبت‌نام شده به تفکیک ادارات');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3055, 'ems_rpt_Minutia_issued' , 'Y' , 'گزارش آماری وضعیت آثار انگشتان کارت‌های تحویل شده  به تفکیک استان');
Insert into GAST_ACCESS (ACS_ID,ACS_NAME,ACS_ENABLED,ACS_COMMENT) values ( 3056, 'ems_rpt_Minutia_issued2' , 'Y' , 'گزارش آماری وضعیت آثار انگشتان کارت‌های تحویل شده  به تفکیک ادارات');
commit;