CREATE SEQUENCE "SEQ_EMS_ABOUT" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_ABOUT 
(
  ABT_ID NUMBER(19, 0) NOT NULL 
, ABT_CREATE_DATE TIMESTAMP(6) NOT NULL 
, ABT_CONTENT VARCHAR2(300 BYTE)
, ABT_PERSON_ID NUMBER(19, 0) NOT NULL 
, CONSTRAINT PK_ABT_ID PRIMARY KEY 
  (
   ABT_ID 
  )

);

ALTER TABLE EMST_ABOUT
ADD CONSTRAINT FK_ABT_PERSON_ID FOREIGN KEY
(
  ABT_PERSON_ID 
)
REFERENCES EMST_PERSON
(
  PER_ID 
)
