CREATE SEQUENCE "SEQ_EMS_HELP" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_HELP 
(
  HLP_ID NUMBER(19, 0) NOT NULL 
, HLP_CREATE_DATE TIMESTAMP(6) NOT NULL 
, HLP_PERSON_ID NUMBER(19, 0) NOT NULL
, HLP_FILE BLOB
, HLP_TITLE VARCHAR2(42 CHAR) NOT NULL 
, HLP_CONTENT_TYPE VARCHAR2(30 CHAR) NOT NULL 
, HLP_DESCRIPTION VARCHAR2(300 CHAR) 
, CONSTRAINT PK_HLP_ID PRIMARY KEY 
  (
   HLP_ID 
  )

);

ALTER TABLE EMST_HELP
ADD CONSTRAINT FK_HLP_PERSON_ID FOREIGN KEY
(
  HLP_PERSON_ID 
)
REFERENCES EMST_PERSON
(
  PER_ID 
)
