CREATE SEQUENCE "SEQ_EMS_OFFICE_SETTING" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE EMST_OFFICE_SETTING 
(
  "OST_ID" NUMBER(19, 0) NOT NULL 
, "OST_ENROLL_OFFICE_ID" NUMBER(19, 0) NOT NULL  
,"OST_NONCONFIRMING_ICAO_IMAGE" NUMBER(1,0) NOT NULL 
,"OST_UPLOAD_PHOTO" NUMBER(1,0) NOT NULL 
,"OST_FINGER_SCAN_SINGLE_MODE" NUMBER(1,0) NOT NULL 
,"OST_DISABILITY_MODE" NUMBER(1,0) NOT NULL 
,"OST_REISSUE_REQUEST" NUMBER(1,0) NOT NULL 
,"OST_ELDERLY_MODE" NUMBER(1,0) NOT NULL 
,"OST_NMOC_GENERATION" NUMBER(1,0) NOT NULL 
,"OST_AMPUTATION_ANNOUNCMENT" NUMBER(1,0) NOT NULL
,"OST_ALLOW_EDIT_BACKGROUND" NUMBER(1,0) NOT NULL 
,"OST_USE_SCANNER_UI" NUMBER(1,0) NOT NULL 
, CONSTRAINT "PK_OST_ID" PRIMARY KEY ("OST_ID" )
, CONSTRAINT "FK_OST_ENROLL_OFFICE_ID" FOREIGN KEY ("OST_ENROLL_OFFICE_ID") REFERENCES EMST_ENROLLMENT_OFFICE ("EOF_ID")  ON DELETE CASCADE ENABLE)
SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "TS_NOCR_EMS";


/*Prerequisite queries*/
INSERT INTO EMST_OFFICE_SETTING (
OST_ID,
OST_ENROLL_OFFICE_ID,
OST_AMPUTATION_ANNOUNCMENT,
OST_DISABILITY_MODE,
OST_ELDERLY_MODE,
OST_FINGER_SCAN_SINGLE_MODE,
OST_NMOC_GENERATION,
OST_NONCONFIRMING_ICAO_IMAGE,
OST_UPLOAD_PHOTO,
OST_ALLOW_EDIT_BACKGROUND,
OST_USE_SCANNER_UI,
OST_REISSUE_REQUEST
)
SELECT 
SEQ_EMS_OFFICE_SETTING.NEXTVAL AS OST_ID,
EOF.EOF_ID AS OST_ENROLL_OFFICE_ID,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_AMPUTATION_ANNOUNCMENT,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_DISABILITY_MODE ,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_ELDERLY_MODE ,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_FINGER_SCAN_SINGLE_MODE ,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_NMOC_GENERATION ,
 0 AS OST_NONCONFIRMING_ICAO_IMAGE ,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_UPLOAD_PHOTO, 
 0 AS OST_ALLOW_EDIT_BACKGROUND,
 0 AS OST_USE_SCANNER_UI ,
(case  EOF.EOF_TYPE when 'NOCR' then 1  else 0 end) AS OST_REISSUE_REQUEST FROM EMST_ENROLLMENT_OFFICE EOF
;