   CREATE TABLE GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP
   (PLM_ID NUMBER(2,0),
	PLM_PROVINCE_NAME VARCHAR2(70 BYTE), 
	PLM_PROVINCE_CODE NUMBER(2,0), 
	PLM_LOC_ID NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

CREATE SEQUENCE GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE  
MINVALUE 1 MAXVALUE 99999 
INCREMENT BY 1 
START WITH 1 CACHE 20 NOORDER NOCYCLE ;

REM INSERTING into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP
SET DEFINE OFF;
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'ایلام',67,1004);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'مرکزی',51,1022);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'زنجان',68,1010);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'گیلان',52,1019);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'چهارمحال وبختیاری',69,1007);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'مازندران',53,1021);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'کهگیلویه وبویراحمد',70,1018);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'آذربایجان شرقی',54,1000);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'سمنان',71,1011);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'آذربایجان غربی',55,1001);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'یزد',72,1025);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'کرمانشاه',56,1016);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'بوشهر',73,1005);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'خوزستان',57,1009);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'تهران',74,1006);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'فارس',58,1013);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'اردبیل',75,1002);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'کرمان',59,1017);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'قم',76,1014);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'خراسان رضوی',60,1008);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'قزوین',77,1027);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'اصفهان',61,1003);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'گلستان',78,1026);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'هرمزگان',62,1023);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'خراسان شمالی',79,1029);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'سیستان وبلوچستان',63,1012);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'خراسان جنوبی',80,1028);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'کردستان',64,1015);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'البرز',81,1030);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'همدان',65,1024);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'دﺳﺘﮕﺎه ﻫﺎي ﺳﺘﺎدي',82,1031);
Insert into GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP (PLM_ID,PLM_PROVINCE_NAME,PLM_PROVINCE_CODE,PLM_LOC_ID) values (GAM_MAIN_EMS.SEQ_EMST_PROVINCE_CODE.NEXTVAL,'لرستان',66,1020);

alter table GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP add constraint EMST_CBI_LOC_ID_PK primary key(PLM_LOC_ID);

alter table GAM_MAIN_EMS.EMST_LOCATION add constraint FK_LOC_PROVINCE_ID_CBI_PROVINCE_CODE 
foreign key(LOC_PROVINCE_ID) references GAM_MAIN_EMS.EMST_CBI_PROVINCE_LOCATION_MAP(PLM_LOC_ID);

CREATE SEQUENCE  GAM_MAIN_EMS.SEQ_EMS_REG_PAYMENT_CODE
MINVALUE 300000000 MAXVALUE 599999999
INCREMENT BY 1
START WITH 300000000 CACHE 1000 NOORDER NOCYCLE ;

INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.cpiDepositId', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '2', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.organizationPaymentCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '0111', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.cpiIncomeCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '140149', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.firstCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '01', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.firstReplicaCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '02', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.secondReplicaCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '03', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.thirdReplicaCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '04', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.replaceCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '05', NULL, NULL);
-- -------------------------------------------------------
INSERT INTO GAM_MAIN_EMS.INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.extendCardPaymentServiceCode', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO GAM_MAIN_EMS.INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (GAM_MAIN_EMS.SEQ_INFT_SYS_PROFILE.NEXTVAL, GAM_MAIN_EMS.SEQ_INFT_PROFILE_KEY.currval, '01', NULL, NULL);
