alter table EMST_PERSON_TOKEN
    add "PTK_REASON" VARCHAR2(255 CHAR);
COMMENT ON COLUMN "EMST_PERSON_TOKEN"."PTK_REASON" IS 'دلیل صدور';
commit ;


ALTER TABLE COMM_DEV_EMS.EMST_REGISTRATION_PAYMENT
  ADD (RPY_TERMINAl_ID  VARCHAR2(50 CHAR));

ALTER TABLE COMM_DEV_EMS.EMST_REGISTRATION_PAYMENT
  ADD (RPY_MERCHANT_ID  VARCHAR2(50 CHAR));





alter table GAM_MAIN_EMS.emst_registration_payment
  add (rpy_payment_type number(1));

alter table gam_main_ems.emst_registration_payment
  add constraint ck_rpy_payment_type check
    (rpy_payment_type in (0,1)) enable;

comment on column gam_main_ems.emst_registration_payment.rpy_payment_type is '1=IPG 2=PCPOS نوع پرداخت';




  CREATE TABLE "EMS_LOG"."EMST_CUSTOME_LOG"
   (	"CTL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CTL_ACTION" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CTL_IS_ACTION_SUCCESS" NUMBER(1,0),
	"CTL_ACTOR" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CTL_ADDITIONAL_DATA" CLOB,
	"CTL_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"CTL_EDITED_VALUE" CLOB,
	"CTL_ENTITY_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CTL_ENTITY_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	 PRIMARY KEY ("CUSTOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("CUSTOM_ADDITIONAL_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING )
 LOB ("CUSTOM_EDITED_VALUE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING ) ;
