alter table EMST_PERSON_TOKEN
    add "PTK_REASON" VARCHAR2(255 CHAR);
COMMENT ON COLUMN "EMST_PERSON_TOKEN"."PTK_REASON" IS 'دلیل صدور';
commit ;


ALTER TABLE COMM_DEV_EMS.EMST_REGISTRATION_PAYMENT
  ADD (RPY_TERMINAl_ID  VARCHAR2(50 CHAR));

ALTER TABLE COMM_DEV_EMS.EMST_REGISTRATION_PAYMENT
  ADD (RPY_MERCHANT_ID  VARCHAR2(50 CHAR));