INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2172', '3', '1', 'nocr.ems.profile.firstCardPaymentAmount', 'P,D,S', 'H');

INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2172', '2172', '200000');

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2173', '3', '1', 'nocr.ems.profile.firstReplicaCardPaymentAmount', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2173', '2173', '400000');

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2174', '3', '1', 'nocr.ems.profile.secondReplicaCardPaymentAmount', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2174', '2174', '700000');

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2175', '3', '1', 'nocr.ems.profile.thirdReplicaCardPaymentAmount', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2175', '2175', '1000000');

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2176', '3', '1', 'nocr.ems.profile.replaceCardPaymentAmount', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2176', '2176', '300000');

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2176', '3', '1', 'nocr.ems.profile.extendCardPaymentAmount', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2176', '2176', '200000');