CREATE TABLE EMST_WORKSTATION_INFO
(
  WSI_ID NUMBER(19, 0) NOT NULL
, WSI_ADDITIONAL_INFO_AS_JSON VARCHAR2(255 CHAR)
, WSI_CCOS_VERSION VARCHAR2(255 CHAR)
, WSI_CPU_INFO VARCHAR2(255 CHAR)
, WSI_GATHER_STATE NUMBER(5, 0) NOT NULL
, WSI_HAS_DOTNET_FRAMWORK45 NUMBER(5, 0)
, WSI_IP_ADDRESS VARCHAR2(255 CHAR)
, WSI_LAST_MODIFIED_DATE TIMESTAMP(6)
, WSI_MEMORY_CAPACITY VARCHAR2(255 CHAR)
, WSI_OS_VERSION VARCHAR2(255 CHAR)
, WSI_USERNAME VARCHAR2(255 CHAR)
, WSI_WORKSTATION_ID NUMBER(19, 0)
, CONSTRAINT SYS_C0034199 PRIMARY KEY
  (
    WSI_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX SYS_C0034199 ON EMST_WORKSTATION_INFO (WSI_ID ASC)
      LOGGING
      TABLESPACE TS_NOCR_EMS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE TS_NOCR_EMS
PCTFREE 10
INITRANS 1
STORAGE
(
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;

ALTER TABLE EMST_WORKSTATION_INFO
ADD CONSTRAINT FK4E392F00E97CE928 FOREIGN KEY
(
  WSI_WORKSTATION_ID
)
REFERENCES EMST_WORKSTATION
(
  WST_ID
)
ENABLE;
