INSERT INTO INFT_PROFILE_KEY (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS, PRF_VALUES, PRF_ICON_CLASS, PRF_PER_ACCESS, PRF_DEP_ACCESS, PRF_SYS_ACCESS)
VALUES (SEQ_INFT_PROFILE_KEY.NEXTVAL, 3, 1, 'nocr.ems.profile.extendValidYearTolerance', 'P,D,S', 'H', NULL, NULL, NULL, NULL, NULL);

INSERT INTO INFT_SYSTEM_PROFILE (SPF_ID, SPF_PRF_ID, SPF_CLOB, SPF_BLOB, SPF_DATE)
VALUES (SEQ_INFT_SYS_PROFILE.NEXTVAL,SEQ_INFT_PROFILE_KEY.currval, '30d', NULL, NULL);