change constraint with name =  CKC_BIM_TYPE in EMST_BIOMETRIC table and add two type FING_NORMAL_1 and FING_NORMAL_2;

INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2190', '3', '1', 'nocr.ems.profile.fingNormal2SizeKB', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2190', '2190', '1.5');


INSERT INTO "COMM_DEV_EMS"."INFT_PROFILE_KEY" (PRF_ID, PRF_PARENT_ID, PRF_SYS_ID, PRF_NAME, PRF_PRIORITY_CHAIN, PRF_STATUS)
VALUES ('2191', '3', '1', 'nocr.ems.profile.fingNormal1SizeKB', 'P,D,S', 'H');
INSERT INTO "COMM_DEV_EMS"."INFT_SYSTEM_PROFILE" (SPF_ID, SPF_PRF_ID, SPF_CLOB) VALUES ('2191', '2191', '1.5');


##########################################################################################################
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


--  There is no statement for index COMM_DEV_EMS.SYS_C0022619.
--  The object is created when the parent object is created.

ALTER TABLE COMM_DEV_EMS.OFFICE_SETTING_FEATURE_EXTRACT ADD (
  PRIMARY KEY
  (OST_ID, FEI_ID)
  USING INDEX
    TABLESPACE TS_NOCR_EMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE COMM_DEV_EMS.OFFICE_SETTING_FEATURE_EXTRACT ADD (
  CONSTRAINT FKFD5D336615A5FCFA
  FOREIGN KEY (OST_ID)
  REFERENCES COMM_DEV_EMS.EMST_OFFICE_SETTING (OST_ID)
  ENABLE VALIDATE,
  CONSTRAINT FKFD5D3366C69C0199
  FOREIGN KEY (FEI_ID)
  REFERENCES COMM_DEV_EMS.EMST_FEATURE_EXTRACT_IDS (FEI_ID)
  ENABLE VALIDATE);

  بر اساس نظر دوستان در تیم تحلیل مقدار رکوردهای این جدل بر اساس مقادیر مورد نظر به ازای هر دفتر پر شود.

#######################################################################################
BMI_FEATURE_EXTRACT_ID_CC این جدول موجود است فقط باید دو فیلد آخر به نام های و
BMI_FEATURE_EXTRACT_ID_NORMAL   به آن اضافه شوند
ALTER TABLE COMM_DEV_EMS.EMST_BIOMETRIC_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE COMM_DEV_EMS.EMST_BIOMETRIC_INFO CASCADE CONSTRAINTS;

CREATE TABLE COMM_DEV_EMS.EMST_BIOMETRIC_INFO
(
  BII_ID                         NUMBER(19)     NOT NULL,
  BII_TYPE                       NUMBER(1),
  BII_MINUTIA_TYPE               NUMBER(1),
  BII_CITIZEN_ID                 NUMBER(19)     NOT NULL,
  BII_FING_QUALITY               NUMBER(1),
  BII_NID                        VARCHAR2(10 CHAR),
  BMI_FEATURE_EXTRACT_ID_CC      VARCHAR2(4 BYTE) DEFAULT '0201' NOT NULL,
  BMI_FEATURE_EXTRACT_ID_NORMAL  VARCHAR2(4 BYTE) DEFAULT '0201' NOT NULL
)
TABLESPACE TS_NOCR_EMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX COMM_DEV_EMS.EMST_BIOMETRIC_INFO_PK ON COMM_DEV_EMS.EMST_BIOMETRIC_INFO
(BII_ID)
LOGGING
TABLESPACE TS_NOCR_EMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE COMM_DEV_EMS.EMST_BIOMETRIC_INFO ADD (
  CONSTRAINT CKC_FING_QUALITY
  CHECK (BII_FING_QUALITY IN ('0', '1', '2', '3'))
  ENABLE VALIDATE,
  CONSTRAINT EMST_BIOMETRIC_INFO_PK
  PRIMARY KEY
  (BII_ID)
  USING INDEX COMM_DEV_EMS.EMST_BIOMETRIC_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE COMM_DEV_EMS.EMST_BIOMETRIC_INFO ADD (
  CONSTRAINT FK_BII_CITIZEN_ID
  FOREIGN KEY (BII_CITIZEN_ID)
  REFERENCES COMM_DEV_EMS.EMST_CITIZEN (CTZ_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
##########################################################################################
این جدول موجود است فقط باید دو فیلد آخر به نام های
OST_ALW_AMPT_FING_STA_ELD=false
و
OST_ALW_CHG_FING_DUR_CAP_ELD=true
برای فیلد اول مقدار پیش فرض  false  و
برای فیلد دوم مقدار پیش فرض true
 واین دو فیلد برای رکوردهای موجود مقدار دهی شوند
ALTER TABLE COMM_DEV_EMS.EMST_OFFICE_SETTING
 DROP PRIMARY KEY CASCADE;

DROP TABLE COMM_DEV_EMS.EMST_OFFICE_SETTING CASCADE CONSTRAINTS;

CREATE TABLE COMM_DEV_EMS.EMST_OFFICE_SETTING
(
  OST_ID                        NUMBER(19)      NOT NULL,
  OST_ENROLL_OFFICE_ID          NUMBER(19)      NOT NULL,
  OST_NONCONFIRMING_ICAO_IMAGE  NUMBER(1)       NOT NULL,
  OST_UPLOAD_PHOTO              NUMBER(1)       NOT NULL,
  OST_FINGER_SCAN_SINGLE_MODE   NUMBER(1)       NOT NULL,
  OST_DISABILITY_MODE           NUMBER(1)       NOT NULL,
  OST_REISSUE_REQUEST           NUMBER(1)       NOT NULL,
  OST_ELDERLY_MODE              NUMBER(1)       NOT NULL,
  OST_NMOC_GENERATION           NUMBER(1)       NOT NULL,
  OST_AMPUTATION_ANNOUNCMENT    NUMBER(1)       NOT NULL,
  OST_ALLOW_EDIT_BACKGROUND     NUMBER(1)       NOT NULL,
  OST_USE_SCANNER_UI            NUMBER(1)       NOT NULL,
  OST_ALW_AMPT_FING_STA_ELD     NUMBER(1)		    NOT NULL,
  OST_ALW_CHG_FING_DUR_CAP_ELD  NUMBER(1)		    NOT NULL
)
TABLESPACE TS_NOCR_EMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX COMM_DEV_EMS.PK_OST_ID ON COMM_DEV_EMS.EMST_OFFICE_SETTING
(OST_ID)
LOGGING
TABLESPACE TS_NOCR_EMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE COMM_DEV_EMS.EMST_OFFICE_SETTING ADD (
  CONSTRAINT PK_OST_ID
  PRIMARY KEY
  (OST_ID)
  USING INDEX COMM_DEV_EMS.PK_OST_ID
  ENABLE VALIDATE);

ALTER TABLE COMM_DEV_EMS.EMST_OFFICE_SETTING ADD (
  CONSTRAINT FK_OST_ENROLL_OFFICE_ID
  FOREIGN KEY (OST_ENROLL_OFFICE_ID)
  REFERENCES COMM_DEV_EMS.EMST_ENROLLMENT_OFFICE (EOF_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);


