INSERT INTO "SABA_DEV_EMS"."INFT_PROFILE_KEY" ("PRF_ID", "PRF_PARENT_ID", "PRF_SYS_ID", "PRF_NAME", "PRF_PRIORITY_CHAIN", "PRF_STATUS", "PRF_VALUES", "PRF_ICON_CLASS", "PRF_PER_ACCESS", "PRF_DEP_ACCESS", "PRF_SYS_ACCESS")
 VALUES (2201, 3, 1, 'nocr.ems.profile.bpiEndpoint', 'P,D,S', 'H', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL')

INSERT INTO "SABA_DEV_EMS"."INFT_PROFILE_KEY" ("PRF_ID", "PRF_PARENT_ID", "PRF_SYS_ID", "PRF_NAME", "PRF_PRIORITY_CHAIN", "PRF_STATUS", "PRF_VALUES", "PRF_ICON_CLASS", "PRF_PER_ACCESS", "PRF_DEP_ACCESS", "PRF_SYS_ACCESS")
VALUES (2202, 3, 1, 'nocr.ems.profile.bpiNamespace', 'S,D,P', 'H', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL')

INSERT INTO "SABA_DEV_EMS"."INFT_SYSTEM_PROFILE" ("SPF_ID", "SPF_PRF_ID", "SPF_CLOB", "SPF_BLOB", "SPF_DATE")
VALUES (2201, 2201, 'http://10.7.17.68:7002/bpi-1.0/BpiService?WSDL', NULL, 'NULL')

INSERT INTO "SABA_DEV_EMS"."INFT_SYSTEM_PROFILE" ("SPF_ID", "SPF_PRF_ID", "SPF_CLOB", "SPF_BLOB", "SPF_DATE")
VALUES (2202, 2202, 'http://bpi.farafan.ir/', NULL, 'NULL')