alter table EMST_OFFICE_SETTING
add	"OST_FEATURE_EXTRACTOR_ID" VARCHAR2(4 CHAR) DEFAULT '1'
/
alter table EMST_OFFICE_SETTING
add"OST_FEATURE_EXTRACTOR_VERSION" VARCHAR2(5 CHAR)  DEFAULT '1'
/
     COMMENT ON COLUMN "EMST_OFFICE_SETTING"."OST_FEATURE_EXTRACTOR_ID" IS 'شناسه الگوریتم مورد استفاده برای استخراج مینوشیا';

   COMMENT ON COLUMN "EMST_OFFICE_SETTING"."OST_FEATURE_EXTRACTOR_VERSION" IS 'ورژن الگوریتم مورد استفاده برای استخراج مینوشیا';
/
alter table EMST_BIOMETRIC_INFO
add"BMI_FEATURE_EXTRACTOR_ID" VARCHAR2(5 CHAR)  DEFAULT '1'
/
   COMMENT ON COLUMN "EMST_BIOMETRIC_INFO"."BMI_FEATURE_EXTRACTOR_ID" IS 'شناسه الگوریتم مورد استفاده برای استخراج مینوشیا';
   /


﻿alter table EMST_OFFICE_CAPACITY
add "EOC_WORKING_HOURS_FROM" NUMBER(4,1)
/
alter table EMST_OFFICE_CAPACITY
add	"EOC_WORKING_HOURS_TO" NUMBER(4,1)
/
   COMMENT ON COLUMN "EMST_OFFICE_CAPACITY"."EOC_WORKING_HOURS_FROM" IS 'ساعت کاری از';

   COMMENT ON COLUMN "EMST_OFFICE_CAPACITY"."EOC_WORKING_HOURS_TO" IS 'ساعت کاری تا';

   

alter table EMST_BIOMETRIC_INFO
add"BMI_FEATURE_EXTRACTOR_ID" VARCHAR2(5 CHAR)  DEFAULT '1'
/ 
   COMMENT ON COLUMN "EMST_BIOMETRIC_INFO"."BMI_FEATURE_EXTRACTOR_ID" IS 'شناسه الگوریتم مورد استفاده برای استخراج مینوشیا';
   /

   
alter table EMST_ENROLLMENT_OFFICE
add "EOF_IS_ACTIVE" NUMBER(1,0) DEFAULT 1
/
 COMMENT ON COLUMN "EMST_ENROLLMENT_OFFICE"."EOF_IS_ACTIVE" IS 'آيا دفتر فعال ميباشد؟';
