  ---------------------------------------------------------------------------------
  
  CREATE TABLE "EMST_MESSAGE"
  (
    "MESS_ID"      NUMBER(19,0) NOT NULL ENABLE,
    "MESS_CREATE_DATE" TIMESTAMP(6) ,
    "MESS_TITLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "MESS_CONTENT" CLOB,
    "MESS_SENDER_USERNAME" varchar2(255 BYTE),
    "MESS_FILE"  BLOB,
    "MESS_HAS_FILE" NUMBER(1,0),
    "MESS_FILE_NAME" VARCHAR2(255 BYTE) ,
    "MESS_FILE_TYPE" VARCHAR2(255 BYTE) ,
    
    CONSTRAINT "EMST_MESSAGE_PK" PRIMARY KEY ("MESS_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING TABLESPACE "TS_NOCR_EMS" ENABLE
  )
	
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "TS_NOCR_EMS" ;
  ---------------------------------------------------------------------------
  CREATE SEQUENCE "SEQ_EMST_MESSAGE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER NOCYCLE ;

  
  ---------------------------------------------------------------------------  
  
  